name: "Nais Setup CLI"
description: "Setup CLI for the Nais platform (Linux only)"
author: "nais"
inputs:
  version:
    description: "Version of nais CLI to install (e.g., 'v3.8.3' or 'latest')"
    required: false
    default: "latest"
  team:
    description: "Default team written to the nais CLI config file"
    required: false
  environment:
    description: "Default environment written to the nais CLI config file"
    required: false
runs:
  using: "node24"
  main: "dist/index.js"
