name: "Nais Setup CLI"
description: "Setup CLI for the Nais platform"
author: "nais"
inputs:
  version:
    description: "Version of nais CLI to install (e.g., 'v3.8.3' or 'latest')"
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Install nais CLI
      shell: bash
      env:
        INPUT_VERSION: ${{ inputs.version }}
        GH_TOKEN: ${{ github.token }}
      run: "$GITHUB_ACTION_PATH/setup.sh"
